# Generated by Django 6.0 on 2025-12-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
